config/routes.rb
Rails.application.routes.draw do

  post "users/add", to:"users#add"
  post "users/login", to: "users#login"
  post "users/addEmail", to: "users#addEmail"
  post "users/delete", to: "users#warmupcleartable"

  post "users/upload", to: "photos#upload"
  
  post "photos/delete", to: "photos#deleteAllPicture"
  get "photos/getPhotos", to: "photos#getPhotos"
  post "photos/vote", to: "photos#vote"
  get "photos/getScore", to: "photos#getScore"
  get "photos/getCaption", to: "photos#getCaption"
  get "photos/getHot", to: "photos#getHot"

  get "pins/getPins", to: "pins#getPins"
  get "pins/getScore", to: "pins#getScore"

  post "/TESTAPI/unitTests", to: "users#warmupstarttests"
  post "/TESTAPI/resetFixture", to: "users#warmupcleartable"
  root to: "users#index";

  get "user/new", to: "users#new" , as: :new_user
  get "user.:id", to: "users#show", as: :user
  post "users", to:"users#create"
  get "users", to:"users#index"
  get 'edit_usersmodel.:id', to: "users#edit", as: :edit_user
  patch "user.:id", to: "users#update"

  resources :sessions

end

app/helpers/usersmodels_helper.rb
module UsersmodelsHelper
end

app/views/usersmodels/_form.html.erb
<%= form_for(@usersmodel) do |f| %>
  <% if @usersmodel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usersmodel.errors.count, "error") %> prohibited this usersmodel from being saved:</h2>

      <ul>
      <% @usersmodel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usersmodels/edit.html.erb
<h1>Editing usersmodel</h1>

<%= render 'form' %>

<%= link_to 'Show', @usersmodel %> |
<%= link_to 'Back', usersmodels_path %>

app/views/usersmodels/index.html.erb
<h1>Listing usersmodels</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Password</th>
      <th>Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usersmodels.each do |usersmodel| %>
      <tr>
        <td><%= usersmodel.user %></td>
        <td><%= usersmodel.password %></td>
        <td><%= usersmodel.count %></td>
        <td><%= link_to 'Show', usersmodel %></td>
        <td><%= link_to 'Edit', edit_usersmodel_path(usersmodel) %></td>
        <td><%= link_to 'Destroy', usersmodel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usersmodel', new_usersmodel_path %>

app/views/usersmodels/new.html.erb
<h1>New usersmodel</h1>

<%= render 'form' %>

<%= link_to 'Back', usersmodels_path %>

app/views/usersmodels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @usersmodel.user %>
</p>

<p>
  <strong>Password:</strong>
  <%= @usersmodel.password %>
</p>

<p>
  <strong>Count:</strong>
  <%= @usersmodel.count %>
</p>

<%= link_to 'Edit', edit_usersmodel_path(@usersmodel) %> |
<%= link_to 'Back', usersmodels_path %>